#!/bin/bash -vx
#SBATCH --partition=kruskal_r6
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH -J m3dc1_2d
#SBATCH -t 0:10:00
#SBATCH --mem 32000

# Partition mesh
part_mesh.sh diiid0.02.smb $SLURM_NTASKS

# Run M3D-C1
rm -f C1stdout
mpiexec --bind-to none -np $SLURM_NTASKS m3dc1_2d_complex -pc_factor_mat_solver_package mumps >& C1stdout
