#!/bin/bash -vx
#PBS -l nodes=1:ppn=1
#PBS -l walltime=04:00:00
#PBS -N m3dc1_adapt
#PBS -l mem=60000mb
#PBS -V

cd $PBS_O_WORKDIR

NPROCS=`wc -l < $PBS_NODEFILE`

/bin/rm -f C1stdout
mpiexec -n $NPROCS m3dc1_2d >& C1stdout
