#!/bin/bash -vx

if   [[ "$M3DC1_ARCH" == "sunfire.r6" ]]; then
#SBATCH --partition=mque
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH -t 4:00:00
#SBATCH --mem 60000
elif [[ "$M3DC1_ARCH" == "saturn" ]]; then
#SBATCH --partition=medium
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH -t 4:00:00
#SBATCH --mem 60000
else
echo "$M3DC1_ARCH not supported"
fi

#SBATCH -J m3dc1_adapt

# Run M3D-C1
/bin/rm -f C1stdout
mpiexec --bind-to none -np 1 m3dc1_2d >& C1stdout
