#!/bin/bash -vx
#PBS -l nodes=1:ppn=16
#PBS -l walltime=01:00:00
#PBS -N m3dc1_equil
#PBS -l mem=120000mb
#PBS -V

cd $PBS_O_WORKDIR

NPROCS=`wc -l < $PBS_NODEFILE`

# Partition mesh
part_mesh.sh adapted.smb $NPROCS

/bin/rm -f C1stdout
mpiexec -n $NPROCS m3dc1_2d_complex -pc_factor_mat_solver_package mumps >& C1stdout
