#!/bin/bash -vx

if   [[ "$M3DC1_ARCH" == "sunfire.r6" ]]; then
#SBATCH --partition=mque
#SBATCH --nodes=1
#SBATCH --ntasks=32
#SBATCH -t 4:00:00
#SBATCH --mem 256000
elif [[ "$M3DC1_ARCH" == "saturn" ]]; then
#SBATCH --partition=medium
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH -t 8:00:00
#SBATCH --mem 120000
else
echo "$M3DC1_ARCH not supported"
fi

#SBATCH -J m3dc1_il

# Partition mesh
part_mesh.sh adapted.smb $SLURM_NTASKS

# Run M3D-C1
rm -f C1stdout
mpiexec --bind-to none -np $SLURM_NTASKS m3dc1_2d_complex -pc_factor_mat_solver_package mumps >& C1stdout
