#!/bin/bash -vx

export OMP_NUM_THREADS=1

# Partition mesh
part_mesh.sh adaptedx.smb $SLURM_NTASKS

# Run M3D-C1
rm -f C1stdout
srun -n $SLURM_NTASKS m3dc1_2d_complex -pc_factor_mat_solver_package mumps >& C1stdout
